#!/usr/bin/php
<?php

	require(dirname(__FILE__) .'/../Core/p10.php');

	if($argc < 2) {
		printf("Usage: %s <base64 string> [base64 string [...]]\n", $argv[0]);
		die();
	}

	for($i = 1; $i < $argc; $i++) {
		printf("%s: %s\n", $argv[$i], base64_to_int($argv[$i]));
	}

