#!/usr/bin/php
<?php

	require(dirname(__FILE__) .'/../Core/p10.php');

	if($argc < 2) {
		printf("Usage: %s <ip address> [ip address [...]]\n", $argv[0]);
		die();
	}

	for($i = 1; $i < $argc; $i++) {
		printf("%s: %s\n", $argv[$i], ip_to_base64($argv[$i]));
	}

